### ISSUE TITLE
News Preview not updating after first preview is generated

### ISSUE THREAD

**Issue by Rowanism** [TheCadien/SuluNewsBundle#22] opened 2022-02-23 10:36 UTC
**Version:** dev-master
**SULU Version:** 2.3.x-dev

### Issue
When adding a News item via `/admin/#/news/de/add/details` and saving it, a preview is generated and displayed in the Preview area as intended, the URL is being changed to `/news/de/1/details` as intended.

Changing the content of the News does not refresh the Preview area.
Manually refreshing it with the Refresh button leaves the content in the Preview area unchanged.

Saving then exiting back to the News List and then editing the News item again will create an updated preview, but subsequent changes are not updated in the Preview area unless the user exits and opens the News item edit view again.

**Comment by Jupi007** [comment] 2022-05-05 10:19
I can confirm the problem.

**Comment by TheCadien** [comment] 2022-05-05 11:47
Thanks for Reporting @Rowanism and @Jupi007 , i will take a look , but I am not sure if this is a bundle problem and not more a problem of the Sulu Preview component

**Comment by TheCadien** [comment] 2022-11-09 22:36
Since the bug is no longer reported by anyone, I am closing the issue for now.

**Closed by TheCadien** 2022-11-09 22:36 UTC
Labels: question
